---
title: "Career Statistics Table Creation"
output: html_notebook
---

# Creating a Career Statistics Table
This notebook goes over the creation of our career statistics table
for the snappa scoreboard project. In this, we will explain the way in which we think about statistics in snappa, the concepts behind the statistics which we can collect with our current level of inputs, and the process to create the table. 

This notebook is, like the project, a work in progress. Many of these values are subject to change as we iterate upon player input and expand the possibility of statistics that we can generate. 

## Our Approach to Snappa Statistics
In order to discuss what we can feasibly collect, it's necessary to establish how the various database tables work together under our current build of the app. All of the tables which we collect during gameplay mirror their counterparts in the cloud, i.e., they have the same column names 

```{r, echo = F}
library(DBI)
library(RPostgres)
library(tidyverse)
library(gt)
# Connect to the database
con <- dbConnect(RPostgres::Postgres(),
                          user = "postgres",
                          password = rstudioapi::askForPassword("connection password"),
                          host = "snappabase.cvoo4ewh2y4x.us-west-1.rds.amazonaws.com",
                          port = 5432,
                          dbname = "Snappa Scoreboard"
       )



# Pull the tables from the database and make them tibbles

players_tbl = tbl(con, "players") %>% collect()
scores_tbl = tbl(con, "scores") %>% collect()
game_stats_tbl = tbl(con, "game_stats") %>% collect()
game_history_tbl = tbl(con, "game_history") %>% collect()



# Present the column names


list("Players" = players_tbl, "Scores" = scores_tbl, 
     "Game Performance" = game_stats_tbl, "Game History" = game_history_tbl) %>% 
  imap_dfr(function(df, id) {
    columns = colnames(df)
    table_name = id
    tibble(table = table_name, 
                       variable = columns)
  }) %>% gt()

```



